name: License header check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run header check
        run: python tools/add_license_headers.py --check --include-tests
